name: cicd and share to docker hub

on:
  push:
    branches:
      - cicd

jobs:
  build_and_share:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from github
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: winnifred/winnifred:latest

